# docker-compose --log-level INFO up --build portable-tomcat9
# docker-compose --log-level INFO up

version: '3'
services:
  portable-tomcat9:
    image: terwer/tomcat9:9.0.65
    container_name: portable-tomcat9
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
     - "TZ=Asia/Shanghai"
    volumes:
      # 挂载宿主机时间，保持容器时间正确
      # - /etc/localtime:/etc/localtime:ro
      # 挂载宿主机配置文件到容器
      - ./www/tomcat/conf:/usr/local/tomcat/conf
      # 挂载宿主机/webapps到容器
      - ./www/tomcat/webapps:/usr/local/tomcat/webapps
      # 日志
      - ./www/tomcat/logs:/usr/local/tomcat/logs
      - ./temp:/temp
      # - /Users/terwer/Documents/java/workspace_v16_release/ekp/WebContent:/UserHome/Documents/java/workspace_v16_release/ekp/WebContent
      # - /Users/terwer/Documents/mydocs/RunJS/RunJS/webapp:/UserHome/Documents/mydocs/RunJS/RunJS/webapp
    stdin_open: true
    tty: true
    restart: "no"
    networks:
      - local-dev

networks:
  local-dev:
    external: true